### PR TITLE
Added fixes and some adaptations for new starlette-version

### PR DESCRIPTION
**Pull request by DmitryBurnaev**
Hello! I've added some updates for new starlette version

- added support for starlette >= 0.21.0 (using httpx instead of requests lib)
- added supported python version

### CODE REVIEW

**Comment by sloria** [comment]
How about we just support starlette>=0.21.0 and drop support for older versions?

If users need support for older versions, they can pin webtest-asgi

**Comment by DmitryBurnaev** [comment]
> How about we just support starlette>=0.21.0 and drop support for older versions?
> 
> If users need support for older versions, they can pin webtest-asgi

Good idea) I'll do this and pin `starlette>=0.21.0` in `setup.py`

**Comment by DmitryBurnaev** [comment]
Done:) could you review this changes, please?

**Review by sloria — APPROVED** [review]

**Comment by sloria** [comment]
thanks!

**Comment by DmitryBurnaev** [comment]
Oh) nice! Will you bump the version and place this into pypi?

**Comment by sloria** [comment]
published in 1.1.0

**Pull request merged**
